---
- name: "Neovim | MacOSX | Dependencies"
  community.general.homebrew:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
      - fzf
      - fd
      - neovim
      - git
      - tar
      - build-essential
      - libstdc++6
     state: present

- name: "Neovim | MacOSX | Install"
  community.general.homebrew:
    name: neovim
    state: present
