---
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
      - fzf
      - fd-find
      - neovim
      - git
      - tar
      - build-essential
      - libstdc++6
    state: present
  become: true
